server:
  port: 9992
  
spring:
  application:
    name: ResourceClient9992
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/ggl_zone?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: guang20010427
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      enabled: true
      # 不限制文件大小
      max-file-size: -1
      # 不限制请求体大小
      max-request-size: -1
      # 临时IO目录
      location: E://GGL-ZONE/tempio9992/
      # 不延迟解析
      resolve-lazily: false
      # 超过1Mb，就IO到临时目录
      file-size-threshold: 1MB

  profiles:
    active: dev

  resources:
    static-locations:
    - file:E:\\GGL-ZONE-resources\

  devtools:
    livereload:
      port: 35733

feign:
  client:
    config:
      default:
        connectTimeout: 3600000
        readTimeout: 3600000
mybatis-plus:
  # configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)  

# seata:
#   tx-service-group: my_test_tx_group
#   config:
#     type: nacos
#     nacos:
#       namespace: public
#       server-addr: 127.0.0.1:8848
#       group: SEATA_GROUP
#       username: nacos
#       password: nacos
#   registry:
#     type: nacos
#     nacos:
#       application: SeataServer
#       server-addr: 127.0.0.1:8848
#       group : SEATA_GROUP
#       namespace: public
#       username: nacos
#       password: nacos
