server:
    port: 8888
spring:
    application:
        name: MessageService8888
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
    redis:
        host: localhost
        port: 6379
        lettuce:
            pool:
                max-active: 20
                max-wait: -1
                max-idle: 5
                min-idle: 0
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    profiles:
        active: dev
    devtools:
        livereload:
            port: 35732
